apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: cops-web-jsonnet
  namespace: argocd 
spec:
  destination:
    namespace: jsonnet 
    server: "https://kubernetes.default.svc"
  project: default 
  source:
    path: src/main
    repoURL: "https://github.com/ribeiro-rodrigo/test-apps.git"
    targetRevision: teste 
    directory:
      jsonnet:
        tlas:
          - name: payload
            code: true
            value: |
              {
                  "type": "webapp",
                  "properties": {
                      "image": {
                          "address": "nginx:latest", 
                          "pull_always": false 
                      },
                      "replicas": 1,
                      "termination_timeout_seconds": 60,  
                      "disruption_budget": "60%", 
                      "workload": "general", 
                      "resources":[
                          {
                              "type": "cpu", 
                              "properties": {
                                  "limit": {
                                      "value": 10, 
                                      "unit": "percent"
                                  }, 
                                  "request" : {
                                      "value": 5, 
                                      "unit": "percent"
                                  }
                              }
                          }, 
                          {
                              "type": "memory", 
                              "properties": {
                                  "limit": {
                                      "value": "250", 
                                      "unit": "M"
                                  }, 
                                  "request": {
                                      "value": "100", 
                                      "unit": "M"
                                  }
                              }
                          }
                      ], 
                      "environments": [
                          {
                              "type": "value",
                              "properties": {
                                  "name": "DB_HOST",
                                  "value": "db.example.com"
                              }
                          }
                      ]
                  },
                  "traits": [
                      {
                          "type": "autoscaling", 
                          "properties": {
                              "min": 1, 
                              "max": 1, 
                              "threshold_cpu_unit": "percent", 
                              "threshold_cpu_value": 80, 
                              "threshold_memory_unit": "percent", 
                              "threshold_memory_value": 80, 
                              "polling_interval": 30,
                              "cooldown_period": 300,
                              "fallback_enabled": false, 
                              "failure_threshold": 3
                          }
                      }, 
                      {
                        "type": "ingress-classifier", 
                        "properties": {
                            "class": "general"
                        }
                      }, 
                      {
                          "type": "ingress",
                          "properties": {
                              "class": "alb", 
                              "private": { 
                                  "endpoints": [
                                      {
                                          "type": "http", 
                                          "properties": {
                                              "host": "meudomain",
                                              "port": 80, 
                                              "domain": "foundation.prod.olxbr.io",
                                              "path": "/"
                                          }
                                      }, 
                                      {
                                          "type": "http", 
                                          "properties": {
                                              "host": "testmginxcopsapps",
                                              "port": 80, 
                                              "domain": "foundation.prod.olxbr.io",
                                              "path": "/teste"
                                          }
                                      }, 
                                      {
                                          "type": "http", 
                                          "properties": {
                                              "host": "testmginxcopsapps",
                                              "port": 80, 
                                              "domain": "foundation.prod.olxbr.io",
                                              "path": "/health"
                                          }
                                      }, 
                                      {
                                          "type": "grpc", 
                                          "properties": {
                                              "host": "grpc-testmginxcopsapps",
                                              "port": 5646, 
                                              "domain": "foundation.prod.olxbr.io"
                                          }
                                      } 
                                  ]
                              }, 
                              "public": {
                                "endpoints": []
                              }
                          }
                      }, 
                      {
                          "type": "cors", 
                          "properties": {
                              "allowed_credentials": true,
                              "allowed_headers": [
                                "DNT",
                                "Keep-Alive",
                                "User-Agent",
                                "X-Requested-With",
                                "If-Modified-Since",
                                "Cache-Control",
                                "Content-Type",
                                "Range",
                                "Authorization"
                              ],
                              "allowed_methods": [
                                "GET",
                                "PUT",
                                "POST",
                                "DELETE",
                                "PATCH",
                                "OPTIONS"
                              ],
                              "allowed_origins": [
                                ""
                              ],
                              "expose_headers": [],
                              "max_age": 1728000 
                          }
                      }, 
                      {
                          "type": "custom_metrics", 
                          "properties": {
                              "port": 80,
                              "path": "/metrics"  
                          }
                      }, 
                      {
                          "type": "healthcheck", 
                          "properties": {
                              "initial_interval_seconds": 10, 
                              "interval_seconds": 30, 
                              "timeout_seconds": 3, 
                              "threshold_failure": 2, 
                              "threshold_success": 2, 
                              "protocol": {
                                  "type": "http", 
                                  "properties": {
                                      "path": "/", 
                                      "timeout": 3, 
                                      "port": 80, 
                                      "command": "echo alo mundo"
                                  }
                              }
                          }
                      }, 
                      {
                          "type": "dns_cache", 
                          "properties": {
                              "force_tcp": true 
                          }
                      }, 
                      {
                          "type": "role", 
                          "properties": {
                              "arn": "arn:myrolearn"
                          }
                      }, 
                      {
                          "type": "anti_affinity", 
                          "properties": {}
                      }
                  ]   
              }

          - name: metadata
            code: true
            value: |
              {
                "team": {
                    "squad_uuid": "uuid-foundation", 
                    "workspace_uuid": "uuid-workspace-foundation"
                }, 
                "labels": {
                    "cluster": "prod-cops-1", 
                    "namespace": "foundation", 
                    "app": "calopsita", 
                    "alias": "app-01"
                }, 
                "internal_host_domain": "cops.olxbr.cloud", 
                "workload_type": "Deployment"
              }

        libs:
          - vendor
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true